ALTER TYPE "RunStatus" ADD VALUE 'QUEUED' BEFORE 'PASSED';
ALTER TYPE "RunStatus" ADD VALUE 'RUNNING' BEFORE 'PASSED';
ALTER TABLE "ExecutionRun" ADD COLUMN "startedAt" TIMESTAMP(3);
ALTER TABLE "ExecutionRun" ADD COLUMN "finishedAt" TIMESTAMP(3);
ALTER TABLE "ExecutionRun" ADD COLUMN "error" TEXT;
