'use client';

import { FormEvent, useEffect, useState } from 'react';

const baseUrl = process.env.NEXT_PUBLIC_API_URL ?? 'http://localhost:3001/v1';
type User = { email: string; name: string | null };
type Organization = { id: string; name: string; members: Array<{ role: string }> };
type Project = { id: string; name: string };

async function request<T>(path: string, token?: string, init?: RequestInit): Promise<T> {
  const response = await fetch(`${baseUrl}${path}`, { ...init, headers: { 'content-type': 'application/json', ...(token ? { authorization: `Bearer ${token}` } : {}), ...init?.headers } });
  const body = await response.json().catch(() => ({}));
  if (!response.ok) throw new Error(body.error?.message ?? 'Request failed');
  return body as T;
}

export default function Workspace() {
  const [token, setToken] = useState<string | null>(null); const [user, setUser] = useState<User | null>(null);
  const [organizations, setOrganizations] = useState<Organization[]>([]); const [projects, setProjects] = useState<Project[]>([]);
  const [organizationId, setOrganizationId] = useState(''); const [projectId, setProjectId] = useState(''); const [message, setMessage] = useState(''); const [busy, setBusy] = useState(false);
  const [document, setDocument] = useState('{\n  "openapi": "3.0.3",\n  "info": { "title": "Pet API", "version": "1.0.0" },\n  "paths": {}\n}');
  async function load(activeToken: string) { const items = await request<Organization[]>('/organizations', activeToken); setOrganizations(items); setOrganizationId((current) => current || items[0]?.id || ''); }
  async function loadProjects(activeToken: string, id: string) { if (!id) return setProjects([]); const items = await request<Project[]>(`/organizations/${id}/projects`, activeToken); setProjects(items); setProjectId((current) => items.some((p) => p.id === current) ? current : (items[0]?.id || '')); }
  useEffect(() => { const saved = localStorage.getItem('api-sentinel-token'); if (saved) request<{ user: User }>('/auth/me', saved).then(({ user: me }) => { setToken(saved); setUser(me); return load(saved); }).catch(() => localStorage.removeItem('api-sentinel-token')); }, []);
  useEffect(() => { if (token) void loadProjects(token, organizationId); }, [token, organizationId]);
  async function auth(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setBusy(true); const form = new FormData(event.currentTarget); try { const result = await request<{ token: string; user: User }>('/auth/register', undefined, { method: 'POST', body: JSON.stringify({ name: form.get('name'), email: form.get('email'), password: form.get('password') }) }); localStorage.setItem('api-sentinel-token', result.token); setToken(result.token); setUser(result.user); await load(result.token); } catch (error) { setMessage(error instanceof Error ? error.message : 'Unable to register'); } finally { setBusy(false); } }
  async function createOrganization(event: FormEvent<HTMLFormElement>) { event.preventDefault(); if (!token) return; setBusy(true); try { const form = new FormData(event.currentTarget); await request('/organizations', token, { method: 'POST', body: JSON.stringify({ name: form.get('name') }) }); await load(token); event.currentTarget.reset(); } catch (error) { setMessage(error instanceof Error ? error.message : 'Unable to create organization'); } finally { setBusy(false); } }
  async function createProject(event: FormEvent<HTMLFormElement>) { event.preventDefault(); if (!token || !organizationId) return; const form = new FormData(event.currentTarget); await request(`/organizations/${organizationId}/projects`, token, { method: 'POST', body: JSON.stringify({ name: form.get('name') }) }); await loadProjects(token, organizationId); event.currentTarget.reset(); }
  async function importSpec(event: FormEvent<HTMLFormElement>) { event.preventDefault(); if (!token || !projectId) return; setBusy(true); try { const form = new FormData(event.currentTarget); await request(`/projects/${projectId}/specifications/imports`, token, { method: 'POST', body: JSON.stringify({ name: form.get('name'), document: JSON.parse(document) }) }); setMessage('Specification imported successfully.'); } catch (error) { setMessage(error instanceof Error ? error.message : 'Unable to import specification'); } finally { setBusy(false); } }
  if (!user) return <main className="workspace auth"><nav><a href="/">API Sentinel</a></nav><section className="panel"><p className="eyebrow">GET STARTED</p><h1>Create your workspace</h1><form onSubmit={auth}><label>Name<input name="name" required /></label><label>Email<input name="email" type="email" required /></label><label>Password<input name="password" type="password" minLength={12} required /></label><button className="button" disabled={busy}>{busy ? 'Creating…' : 'Create account'}</button></form>{message && <p className="notice">{message}</p>}</section></main>;
  return <main className="workspace"><nav><a href="/">API Sentinel</a><span className="muted">{user.email}</span><button className="link-button" onClick={() => { localStorage.removeItem('api-sentinel-token'); setUser(null); }}>Sign out</button></nav><header><p className="eyebrow">WORKSPACE</p><h1>Import and review your API contracts.</h1></header><section className="workspace-grid"><article className="panel"><h2>Organization</h2><select value={organizationId} onChange={(e) => setOrganizationId(e.target.value)}><option value="">Select organization</option>{organizations.map((o) => <option key={o.id} value={o.id}>{o.name} ({o.members[0]?.role})</option>)}</select><form onSubmit={createOrganization}><label>New organization<input name="name" minLength={2} required /></label><button className="button secondary" disabled={busy}>Create</button></form></article><article className="panel"><h2>Project</h2><select value={projectId} onChange={(e) => setProjectId(e.target.value)} disabled={!organizationId}><option value="">Select project</option>{projects.map((p) => <option key={p.id} value={p.id}>{p.name}</option>)}</select><form onSubmit={createProject}><label>New project<input name="name" minLength={2} required disabled={!organizationId} /></label><button className="button secondary" disabled={!organizationId}>Create</button></form></article></section><section className="panel import-panel"><h2>Import OpenAPI 3.x</h2><form onSubmit={importSpec}><label>Specification name<input name="name" defaultValue="Pet API" required /></label><label>OpenAPI JSON<textarea value={document} onChange={(e) => setDocument(e.target.value)} /></label><button className="button" disabled={busy || !projectId}>{busy ? 'Importing…' : 'Import specification'}</button></form></section>{message && <p className="notice">{message}</p>}</main>;
}
